<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <modelVersion>4.0.0</modelVersion>
    <parent><groupId>com.feisheng.bot</groupId><artifactId>feisheng-bot-parent</artifactId><version>1.0.0-SNAPSHOT</version></parent>
    <artifactId>feisheng-bot-gateway</artifactId>
    <dependencies>
        <dependency><groupId>com.feisheng.bot</groupId><artifactId>feisheng-bot-common</artifactId><version>${project.version}</version></dependency>
        <dependency><groupId>com.feisheng.bot</groupId><artifactId>feisheng-bot-core</artifactId><version>${project.version}</version></dependency>
        <dependency><groupId>org.springframework.boot</groupId><artifactId>spring-boot-starter-web</artifactId></dependency>
        <dependency><groupId>org.springframework.retry</groupId><artifactId>spring-retry</artifactId></dependency>
        <dependency><groupId>org.springframework.boot</groupId><artifactId>spring-boot-starter-aop</artifactId></dependency>
        <dependency>
            <groupId>com.dingtalk.open</groupId>
            <artifactId>dingtalk-stream</artifactId>
            <version>1.3.7</version>
        </dependency>
        <dependency><groupId>org.projectlombok</groupId><artifactId>lombok</artifactId><optional>true</optional></dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>
