-- feisheng_bot_db schema
SET NAMES utf8mb4;
CREATE DATABASE IF NOT EXISTS feisheng_bot_db DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE feisheng_bot_db;

CREATE TABLE sys_user (id BIGINT AUTO_INCREMENT PRIMARY KEY, username VARCHAR(50) NOT NULL UNIQUE, password VARCHAR(255) NOT NULL, real_name VARCHAR(50), email VARCHAR(100), phone VARCHAR(20), avatar VARCHAR(500), status TINYINT DEFAULT 1, create_time DATETIME DEFAULT CURRENT_TIMESTAMP, update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, deleted TINYINT DEFAULT 0, INDEX idx_username(username)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE sys_role (id BIGINT AUTO_INCREMENT PRIMARY KEY, role_name VARCHAR(50) NOT NULL, role_key VARCHAR(50) NOT NULL UNIQUE, status TINYINT DEFAULT 1, create_time DATETIME DEFAULT CURRENT_TIMESTAMP, update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, deleted TINYINT DEFAULT 0) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE sys_permission (id BIGINT AUTO_INCREMENT PRIMARY KEY, parent_id BIGINT DEFAULT 0, name VARCHAR(100) NOT NULL, permission VARCHAR(200), path VARCHAR(200), type TINYINT, icon VARCHAR(100), sort INT DEFAULT 0, status TINYINT DEFAULT 1, create_time DATETIME DEFAULT CURRENT_TIMESTAMP, deleted TINYINT DEFAULT 0, INDEX idx_parent(parent_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE sys_operation_log (id BIGINT AUTO_INCREMENT PRIMARY KEY, user_id BIGINT, username VARCHAR(50), action VARCHAR(100), target VARCHAR(200), ip VARCHAR(50), params TEXT, result VARCHAR(500), create_time DATETIME DEFAULT CURRENT_TIMESTAMP, INDEX idx_user(user_id), INDEX idx_time(create_time)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE sys_user_role (id BIGINT AUTO_INCREMENT PRIMARY KEY, user_id BIGINT NOT NULL, role_id BIGINT NOT NULL, UNIQUE KEY uk_user_role(user_id, role_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE sys_role_permission (id BIGINT AUTO_INCREMENT PRIMARY KEY, role_id BIGINT NOT NULL, permission_id BIGINT NOT NULL, UNIQUE KEY uk_role_perm(role_id, permission_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE bot_channel_config (id BIGINT AUTO_INCREMENT PRIMARY KEY, channel_type VARCHAR(20) NOT NULL, channel_name VARCHAR(100), config_json TEXT, status TINYINT DEFAULT 1, create_time DATETIME DEFAULT CURRENT_TIMESTAMP, update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, deleted TINYINT DEFAULT 0, INDEX idx_channel_type(channel_type)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE bot_channel_message (id BIGINT AUTO_INCREMENT PRIMARY KEY, channel_type VARCHAR(20), channel_msg_id VARCHAR(100), channel_user_id VARCHAR(100), content TEXT, raw_data TEXT, create_time DATETIME DEFAULT CURRENT_TIMESTAMP, UNIQUE KEY uk_channel_msg(channel_type, channel_msg_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE bot_channel_user (id BIGINT AUTO_INCREMENT PRIMARY KEY, channel_type VARCHAR(20), channel_user_id VARCHAR(100) NOT NULL, nickname VARCHAR(100), avatar VARCHAR(500), create_time DATETIME DEFAULT CURRENT_TIMESTAMP, UNIQUE KEY uk_channel_user(channel_type, channel_user_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE bot_conversation (id BIGINT AUTO_INCREMENT PRIMARY KEY, channel_type VARCHAR(20), channel_user_id VARCHAR(100), title VARCHAR(200), status VARCHAR(20) DEFAULT 'active', create_time DATETIME DEFAULT CURRENT_TIMESTAMP, update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, deleted TINYINT DEFAULT 0, INDEX idx_status(status), INDEX idx_channel(channel_type, channel_user_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE bot_message (id BIGINT AUTO_INCREMENT PRIMARY KEY, conversation_id BIGINT NOT NULL, role VARCHAR(20), content_type VARCHAR(20) DEFAULT 'text', content TEXT, metadata TEXT, create_time DATETIME DEFAULT CURRENT_TIMESTAMP, INDEX idx_conversation(conversation_id), INDEX idx_time(create_time)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE bot_conversation_tag (id BIGINT AUTO_INCREMENT PRIMARY KEY, conversation_id BIGINT NOT NULL, tag_name VARCHAR(50), create_time DATETIME DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE bot_ai_model_config (id BIGINT AUTO_INCREMENT PRIMARY KEY, model_name VARCHAR(100) NOT NULL, provider VARCHAR(50), api_url VARCHAR(500), api_key VARCHAR(500), model_type VARCHAR(20), parameters TEXT, status TINYINT DEFAULT 1, is_default TINYINT DEFAULT 0, create_time DATETIME DEFAULT CURRENT_TIMESTAMP, update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, deleted TINYINT DEFAULT 0) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE bot_ai_reply_log (id BIGINT AUTO_INCREMENT PRIMARY KEY, message_id BIGINT, model_name VARCHAR(100), prompt TEXT, reply TEXT, tokens_input INT DEFAULT 0, tokens_output INT DEFAULT 0, latency_ms INT DEFAULT 0, success TINYINT DEFAULT 1, create_time DATETIME DEFAULT CURRENT_TIMESTAMP, INDEX idx_message(message_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE bot_intent (id BIGINT AUTO_INCREMENT PRIMARY KEY, intent_name VARCHAR(100) NOT NULL, intent_keywords TEXT, reply_template TEXT, status TINYINT DEFAULT 1, create_time DATETIME DEFAULT CURRENT_TIMESTAMP, deleted TINYINT DEFAULT 0) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS bot_forbidden_rule (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  rule_type VARCHAR(30) NOT NULL COMMENT 'SENSITIVE_WORD/FORBIDDEN_TOPIC/FORCE_HANDOFF/AI_DISCLAIMER',
  pattern TEXT NOT NULL COMMENT '匹配模式(普通文本或正则)',
  is_regex TINYINT DEFAULT 0 COMMENT '是否正则表达式',
  action VARCHAR(20) NOT NULL COMMENT 'BLOCK/REPLY_FIXED/HANDOFF/LOG_ONLY',
  reply_text TEXT COMMENT 'action=REPLY_FIXED时的固定回复',
  description VARCHAR(500) COMMENT '规则说明',
  is_enabled TINYINT DEFAULT 1,
  priority INT DEFAULT 0 COMMENT '优先级(数字小的先匹配)',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted TINYINT DEFAULT 0,
  INDEX idx_type_enabled(rule_type, is_enabled),
  INDEX idx_priority(priority)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE bot_reply_strategy (id BIGINT AUTO_INCREMENT PRIMARY KEY, strategy_name VARCHAR(100), priority INT DEFAULT 0, rule_condition TEXT, action VARCHAR(50), status TINYINT DEFAULT 1, create_time DATETIME DEFAULT CURRENT_TIMESTAMP, deleted TINYINT DEFAULT 0) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE bot_knowledge_category (id BIGINT AUTO_INCREMENT PRIMARY KEY, parent_id BIGINT DEFAULT 0, name VARCHAR(200) NOT NULL, sort INT DEFAULT 0, status TINYINT DEFAULT 1, create_time DATETIME DEFAULT CURRENT_TIMESTAMP, update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, deleted TINYINT DEFAULT 0, INDEX idx_parent(parent_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE bot_knowledge_item (id BIGINT AUTO_INCREMENT PRIMARY KEY, category_id BIGINT DEFAULT 0, question VARCHAR(500) NOT NULL, answer TEXT, keywords VARCHAR(500), status TINYINT DEFAULT 1, hit_count INT DEFAULT 0, create_time DATETIME DEFAULT CURRENT_TIMESTAMP, update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, deleted TINYINT DEFAULT 0, INDEX idx_category(category_id), INDEX idx_status(status)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE bot_knowledge_document (id BIGINT AUTO_INCREMENT PRIMARY KEY, title VARCHAR(200) NOT NULL, file_name VARCHAR(200), file_path VARCHAR(500), file_size BIGINT DEFAULT 0, category_id BIGINT DEFAULT 0, status TINYINT DEFAULT 1, create_time DATETIME DEFAULT CURRENT_TIMESTAMP, deleted TINYINT DEFAULT 0) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE bot_knowledge_chunk (id BIGINT AUTO_INCREMENT PRIMARY KEY, document_id BIGINT NOT NULL, chunk_index INT DEFAULT 0, content TEXT, create_time DATETIME DEFAULT CURRENT_TIMESTAMP, INDEX idx_document(document_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE bot_ticket (id BIGINT AUTO_INCREMENT PRIMARY KEY, conversation_id BIGINT, title VARCHAR(200), description TEXT, status VARCHAR(20) DEFAULT 'pending', priority VARCHAR(10) DEFAULT 'normal', assignee_id BIGINT, create_time DATETIME DEFAULT CURRENT_TIMESTAMP, update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, deleted TINYINT DEFAULT 0, INDEX idx_status(status), INDEX idx_conversation(conversation_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE bot_ticket_record (id BIGINT AUTO_INCREMENT PRIMARY KEY, ticket_id BIGINT NOT NULL, operator_id BIGINT, action VARCHAR(50), content TEXT, create_time DATETIME DEFAULT CURRENT_TIMESTAMP, INDEX idx_ticket(ticket_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE bot_daily_statistics (id BIGINT AUTO_INCREMENT PRIMARY KEY, stat_date DATE NOT NULL, conversation_count INT DEFAULT 0, message_count INT DEFAULT 0, faq_hit_count INT DEFAULT 0, ai_reply_count INT DEFAULT 0, transfer_count INT DEFAULT 0, create_time DATETIME DEFAULT CURRENT_TIMESTAMP, UNIQUE KEY uk_date(stat_date)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Customer
CREATE TABLE IF NOT EXISTS bot_customer (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100),
  phone VARCHAR(20),
  email VARCHAR(100),
  channel_type VARCHAR(20),
  channel_user_id VARCHAR(100),
  nickname VARCHAR(100),
  avatar VARCHAR(500),
  total_conversations INT DEFAULT 0,
  last_contact_time DATETIME,
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted TINYINT DEFAULT 0,
  UNIQUE KEY uk_channel_user(channel_type, channel_user_id),
  INDEX idx_name(name),
  INDEX idx_phone(phone)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
