-- Review-only FAQ drafts generated from real unmatched-question clusters.
CREATE TABLE IF NOT EXISTS bot_faq_draft (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  run_id BIGINT NOT NULL,
  cluster_id BIGINT NOT NULL,
  question VARCHAR(500) NOT NULL,
  answer TEXT,
  keywords VARCHAR(500),
  similar_questions_json LONGTEXT,
  evidence_json LONGTEXT,
  evidence_status VARCHAR(20) NOT NULL DEFAULT 'MISSING',
  generation_message VARCHAR(1000),
  generator_model VARCHAR(200),
  duplicate_item_id BIGINT,
  duplicate_score DECIMAL(8,6),
  status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
  created_by BIGINT,
  reviewed_by BIGINT,
  reviewed_at DATETIME,
  review_reason VARCHAR(1000),
  published_item_id BIGINT,
  published_at DATETIME,
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted TINYINT NOT NULL DEFAULT 0,
  UNIQUE KEY uk_faq_draft_cluster(cluster_id),
  INDEX idx_faq_draft_run(run_id),
  INDEX idx_faq_draft_status(status),
  INDEX idx_faq_draft_published_item(published_item_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
